name: "PatchworkFight"
health_estimator: BURST_AND_EXECUTE
time_target: 300000
time_variance: 0.10
events {
  timestamp: 0
  spawn {
    enemy {
      id: 1
      name: "Patchwork"
      type: BOSS
      health_estimator: BURST_AND_EXECUTE
    }
  }
}
events {
  timestamp: 500
  lust {
    haste_percentage: 0.30
  }
}
