encounter_config {
  name: "Two Targets (Cleave)"
  events {
    timestamp: -1
    spawn {
      actor {
        id: 1
        name: "Shatug"
        hp_max: 1000
        hp_current: 1000
      }
      despawn_timestamp: -1
    }
  events {
    timestamp: -1
    spawn {
      actor {
        id: 2
        name: "F'Harg"
        hp_max: 1000
        hp_current: 1000
      }
      despawn_timestamp: -1
    }

  }
}
