cc_proto_library(
    name = "common_cc_protos",
    visibility = ["//visibility:public"],
    deps = [":common_protos"],
)

proto_library(
    name = "common_protos",
    srcs = [
        "actor.proto",
        "encounter.proto",
        "equipment.proto",
        "policy.proto",
        "simulation.proto",
        "talents.proto",
    ],
    visibility = ["//visibility:public"],
)
