-- This sub code was programmatically added by update_flatbuffers.py
local _, Portunus = ...
local function require(m) local e=Portunus.Modules[m] if e==nil then error("Failed to load module " .. m) end return e end
local function export_fn()

--[[ game_state_schema.Cooldown

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 24.3.25

  Declared by  : 
  Rooting type : game_state_schema.GameState ()

--]]

local flatbuffers = require('flatbuffers')

local Cooldown = {}
local mt = {}

function Cooldown.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:SpellId()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Uint32, self.view.pos + o)
  end
  return 0
end

function mt:Ready()
  local o = self.view:Offset(6)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Uint32, self.view.pos + o)
  end
  return 0
end

function mt:Charges()
  local o = self.view:Offset(8)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Uint8, self.view.pos + o)
  end
  return 0
end

function Cooldown.Start(builder)
  builder:StartObject(3)
end

function Cooldown.AddSpellId(builder, spellId)
  builder:PrependUint32Slot(0, spellId, 0)
end

function Cooldown.AddReady(builder, ready)
  builder:PrependUint32Slot(1, ready, 0)
end

function Cooldown.AddCharges(builder, charges)
  builder:PrependUint8Slot(2, charges, 0)
end

function Cooldown.End(builder)
  return builder:EndObject()
end

return Cooldown
end
Portunus.Modules["game_state_schema.Cooldown"]=export_fn()
