-- This sub code was programmatically added by update_flatbuffers.py
local _, Portunus = ...
local function require(m) local e=Portunus.Modules[m] if e==nil then error("Failed to load module " .. m) end return e end
local function export_fn()

--[[ game_state_schema.EnemyUnit

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 24.3.25

  Declared by  : 
  Rooting type : game_state_schema.GameState ()

--]]

local __game_state_schema_UnitBaseInfo = require('game_state_schema.UnitBaseInfo')
local flatbuffers = require('flatbuffers')

local EnemyUnit = {}
local mt = {}

function EnemyUnit.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:BaseInfo()
  local o = self.view:Offset(4)
  if o ~= 0 then
    local x = self.view:Indirect(self.view.pos + o)
    local obj = __game_state_schema_UnitBaseInfo.New()
    obj:Init(self.view.bytes, x)
    return obj
  end
end

function mt:Name()
  local o = self.view:Offset(6)
  if o ~= 0 then
    return self.view:String(self.view.pos + o)
  end
end

function mt:InCombat()
  local o = self.view:Offset(8)
  if o ~= 0 then
    return (self.view:Get(flatbuffers.N.Bool, self.view.pos + o) ~=0)
  end
  return false
end

function mt:Attackable()
  local o = self.view:Offset(10)
  if o ~= 0 then
    return (self.view:Get(flatbuffers.N.Bool, self.view.pos + o) ~=0)
  end
  return false
end

function mt:ThreatSituation()
  local o = self.view:Offset(12)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Uint8, self.view.pos + o)
  end
  return 0
end

function EnemyUnit.Start(builder)
  builder:StartObject(5)
end

function EnemyUnit.AddBaseInfo(builder, baseInfo)
  builder:PrependStructSlot(0, baseInfo, 0)
end

function EnemyUnit.AddName(builder, name)
  builder:PrependUOffsetTRelativeSlot(1, name, 0)
end

function EnemyUnit.AddInCombat(builder, inCombat)
  builder:PrependBoolSlot(2, inCombat, false)
end

function EnemyUnit.AddAttackable(builder, attackable)
  builder:PrependBoolSlot(3, attackable, false)
end

function EnemyUnit.AddThreatSituation(builder, threatSituation)
  builder:PrependUint8Slot(4, threatSituation, 0)
end

function EnemyUnit.End(builder)
  return builder:EndObject()
end

return EnemyUnit
end
Portunus.Modules["game_state_schema.EnemyUnit"]=export_fn()
