-- This sub code was programmatically added by update_flatbuffers.py
-- It is intended to replace the `require` functionality missing from the WOW lua environment.
-- We wrap the entire module in an function called "export_fn()" and then load that fn into Portunus.Modules at the bottom of this file.
local _, Portunus = ...
local function require(m) local e=Portunus.Modules[m] if e==nil then error("Failed to load module " .. m) end return e end
local function export_fn()

--[[ game_state_schema.GameState

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 24.3.25

  Declared by  : 
  Rooting type : game_state_schema.GameState ()

--]]

local __game_state_schema_EnemyUnit = require('game_state_schema.EnemyUnit')
local __game_state_schema_PlayerUnit = require('game_state_schema.PlayerUnit')
local flatbuffers = require('flatbuffers')

local GameState = {}
local mt = {}

function GameState.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function GameState.GetRootAsGameState(buf, offset)
  if type(buf) == "string" then
    buf = flatbuffers.binaryArray.New(buf)
  end

  local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
  local o = GameState.New()
  o:Init(buf, n + offset)
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:SnapshotTimeMs()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Uint32, self.view.pos + o)
  end
  return 0
end

function mt:TargetGuid()
  local o = self.view:Offset(6)
  if o ~= 0 then
    return self.view:String(self.view.pos + o)
  end
end

function mt:Player()
  local o = self.view:Offset(8)
  if o ~= 0 then
    local x = self.view:Indirect(self.view.pos + o)
    local obj = __game_state_schema_PlayerUnit.New()
    obj:Init(self.view.bytes, x)
    return obj
  end
end

function mt:VisibleTargets(j)
  local o = self.view:Offset(10)
  if o ~= 0 then
    local x = self.view:Vector(o)
    x = x + ((j-1) * 4)
    x = self.view:Indirect(x)
    local obj = __game_state_schema_EnemyUnit.New()
    obj:Init(self.view.bytes, x)
    return obj
  end
end

function mt:VisibleTargetsLength()
  local o = self.view:Offset(10)
  if o ~= 0 then
    return self.view:VectorLen(o)
  end
  return 0
end

function GameState.Start(builder)
  builder:StartObject(4)
end

function GameState.AddSnapshotTimeMs(builder, snapshotTimeMs)
  builder:PrependUint32Slot(0, snapshotTimeMs, 0)
end

function GameState.AddTargetGuid(builder, targetGuid)
  builder:PrependUOffsetTRelativeSlot(1, targetGuid, 0)
end

function GameState.AddPlayer(builder, player)
  builder:PrependStructSlot(2, player, 0)
end

function GameState.AddVisibleTargets(builder, visibleTargets)
  builder:PrependUOffsetTRelativeSlot(3, visibleTargets, 0)
end

function GameState.StartVisibleTargetsVector(builder, numElems)
  return builder:StartVector(4, numElems, 4)
end

function GameState.End(builder)
  return builder:EndObject()
end

return GameState
end
-- The above `end` keyword and the following line are designed to replace the `require` functionality missing from the WOW lua environment.
Portunus.Modules["game_state_schema.GameState"]=export_fn()
