-- This sub code was programmatically added by update_flatbuffers.py
local _, Portunus = ...
local function require(m) local e=Portunus.Modules[m] if e==nil then error("Failed to load module " .. m) end return e end
local function export_fn()

--[[ game_state_schema.Resource

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 24.3.25

  Declared by  : 
  Rooting type : game_state_schema.GameState ()

--]]

local flatbuffers = require('flatbuffers')

local Resource = {}
local mt = {}

function Resource.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:ResourceType()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Int8, self.view.pos + o)
  end
  return 0
end

function mt:Current()
  local o = self.view:Offset(6)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Uint8, self.view.pos + o)
  end
  return 0
end

function mt:Maximum()
  local o = self.view:Offset(8)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Uint8, self.view.pos + o)
  end
  return 0
end

function Resource.Start(builder)
  builder:StartObject(3)
end

function Resource.AddResourceType(builder, resourceType)
  builder:PrependInt8Slot(0, resourceType, 0)
end

function Resource.AddCurrent(builder, current)
  builder:PrependUint8Slot(1, current, 0)
end

function Resource.AddMaximum(builder, maximum)
  builder:PrependUint8Slot(2, maximum, 0)
end

function Resource.End(builder)
  return builder:EndObject()
end

return Resource
end
Portunus.Modules["game_state_schema.Resource"]=export_fn()
