-- This sub code was programmatically added by update_flatbuffers.py
local _, Portunus = ...
local function require(m) local e=Portunus.Modules[m] if e==nil then error("Failed to load module " .. m) end return e end
local function export_fn()

--[[ game_state_schema.UnitBaseInfo

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 24.3.25

  Declared by  : 
  Rooting type : game_state_schema.GameState ()

--]]

local __game_state_schema_Aura = require('game_state_schema.Aura')
local flatbuffers = require('flatbuffers')

local UnitBaseInfo = {}
local mt = {}

function UnitBaseInfo.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:UintGuid()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:String(self.view.pos + o)
  end
end

function mt:HealthCurrent()
  local o = self.view:Offset(6)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Uint32, self.view.pos + o)
  end
  return 0
end

function mt:HealthMaximum()
  local o = self.view:Offset(8)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Uint32, self.view.pos + o)
  end
  return 0
end

function mt:Speed()
  local o = self.view:Offset(10)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Float32, self.view.pos + o)
  end
  return 0.0
end

function mt:Buffs(j)
  local o = self.view:Offset(12)
  if o ~= 0 then
    local x = self.view:Vector(o)
    x = x + ((j-1) * 4)
    x = self.view:Indirect(x)
    local obj = __game_state_schema_Aura.New()
    obj:Init(self.view.bytes, x)
    return obj
  end
end

function mt:BuffsLength()
  local o = self.view:Offset(12)
  if o ~= 0 then
    return self.view:VectorLen(o)
  end
  return 0
end

function mt:Debuffs(j)
  local o = self.view:Offset(14)
  if o ~= 0 then
    local x = self.view:Vector(o)
    x = x + ((j-1) * 4)
    x = self.view:Indirect(x)
    local obj = __game_state_schema_Aura.New()
    obj:Init(self.view.bytes, x)
    return obj
  end
end

function mt:DebuffsLength()
  local o = self.view:Offset(14)
  if o ~= 0 then
    return self.view:VectorLen(o)
  end
  return 0
end

function UnitBaseInfo.Start(builder)
  builder:StartObject(6)
end

function UnitBaseInfo.AddUintGuid(builder, uintGuid)
  builder:PrependUOffsetTRelativeSlot(0, uintGuid, 0)
end

function UnitBaseInfo.AddHealthCurrent(builder, healthCurrent)
  builder:PrependUint32Slot(1, healthCurrent, 0)
end

function UnitBaseInfo.AddHealthMaximum(builder, healthMaximum)
  builder:PrependUint32Slot(2, healthMaximum, 0)
end

function UnitBaseInfo.AddSpeed(builder, speed)
  builder:PrependFloat32Slot(3, speed, 0.0)
end

function UnitBaseInfo.AddBuffs(builder, buffs)
  builder:PrependUOffsetTRelativeSlot(4, buffs, 0)
end

function UnitBaseInfo.StartBuffsVector(builder, numElems)
  return builder:StartVector(4, numElems, 4)
end

function UnitBaseInfo.AddDebuffs(builder, debuffs)
  builder:PrependUOffsetTRelativeSlot(5, debuffs, 0)
end

function UnitBaseInfo.StartDebuffsVector(builder, numElems)
  return builder:StartVector(4, numElems, 4)
end

function UnitBaseInfo.End(builder)
  return builder:EndObject()
end

return UnitBaseInfo
end
Portunus.Modules["game_state_schema.UnitBaseInfo"]=export_fn()
