package(default_visibility = ["//visibility:public"])

cc_library(
    name = "engine",
    srcs = [
        "action.h",
        "policy.h",
    ],
    hdrs = [
        "action.h",
        "policy.h",
    ],
    deps = [
        "@com_google_absl//absl/strings",
        "@com_google_glog//:glog",
    ],
)
