from datetime import datetime
from portunus import db, login_manager, bcrypt
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, index=True, nullable=False)
    email = db.Column(db.String(255), unique=True, index=True, nullable=False)
    date_created_utc = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    password_hash = db.Column(db.String(60), nullable=False)
    biography = db.Column(db.String(140), default="No biography set for this user yet.")

    owned_routes = db.relationship(
        "Route", backref=db.backref("owner", lazy=True), lazy="dynamic",
    )
    owned_characters = db.relationship(
        "Character", backref=db.backref("owner", lazy=True), lazy="dynamic",
    )
    owned_teams = db.relationship(
        "Team", backref=db.backref("owner", lazy=True), lazy="dynamic",
    )

    def __repr__(self):
        return f"User('{self.username}', '{self.email}')"

    def set_password(self, password):
        self.password_hash = bcrypt.generate_password_hash(password).decode("utf-8")

    def check_password(self, password):
        return bcrypt.check_password_hash(self.password_hash, password)


class Route(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    owner_user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    title = db.Column(db.String(100), index=True, nullable=False)
    date_created_utc = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"Route('{self.title}')"


# Association table for many-to-many Table <--> Character mapping
team_membership = db.Table(
    "team_membership",
    db.Column("team_id", db.Integer, db.ForeignKey("team.id"), primary_key=True),
    db.Column(
        "character_id", db.Integer, db.ForeignKey("character.id"), primary_key=True
    ),
)


class Team(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    owner_user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    name = db.Column(db.String(20), index=True, nullable=False)
    date_created_utc = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    members = db.relationship(
        "Character",
        secondary=team_membership,
        backref=db.backref("teams", lazy="dynamic"),
        lazy="dynamic",
    )

    def add_character(self, character):
        if not self.contains_character(character):
            self.members.append(character)

    def remove_character(self, character):
        if self.contains_character(character):
            self.members.remove(character)

    def contains_character(self, character):
        return (
            self.members.filter(team_membership.c.character_id == character.id).count() > 0
        )

    def __repr__(self):
        return f"Team('{self.name}', owned by user_id '{self.owner_user_id}')"


class Character(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    owner_user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    server = db.Column(db.String(50), index=True, nullable=False)
    name = db.Column(db.String(20), index=True, nullable=False)
    spec = db.Column(db.Integer, index=True, nullable=False)

    # Relationships
    # owner autogenerated from User model
    # (backhalf is already defined above)

    def __repr__(self):
        return f"Character({self.server}-{self.name} (spec: {self.spec}) owned by user_id {self.owner_user_id})"

